version: '3'
services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - APPLICATION_SECRET
    depends_on:
      - redis
  redis:
    image: redis:latest
    volumes:
      - ./redis-data:/data
